### ISSUE TITLE
ios error

### ISSUE THREAD

**Issue by amin1softco** [TGMTProto/MTProtoProxy#17]
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at MTProtoProxy.MTProtoProxyServer.MTPClientCreated(Object sender, Int32 dcId)

**Comment by TGMTProrto** [comment]
Use the new version(1.0.5-alpha)

**Comment by amin1softco** [comment]
seems work tnx.
