### ISSUE TITLE
not stable 

### ISSUE THREAD

**Issue by amin1softco** [TGMTProto/MTProtoProxy#18]
after 10 user connection  not respond to any other...

**Comment by amin1softco** [comment]
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at MTProtoProxy.TgSockets.GetSocket(Int32& dcId)
   at MTProtoProxy.MTProtoSocket.StartAsync(Byte[]& buffer, String& secret)
   at MTProtoProxy.MTProtoProxyServer.SocketAccepted(Socket socket)
A new connection was created
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at MTProtoProxy.TgSockets.GetSocket(Int32& dcId)
   at MTProtoProxy.MTProtoSocket.StartAsync(Byte[]& buffer, String& secret)
   at MTProtoProxy.MTProtoProxyServer.SocketAccepted(Socket socket)
A new connection was created
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at MTProtoProxy.TgSockets.GetSocket(Int32& dcId)
   at MTProtoProxy.MTProtoSocket.StartAsync(Byte[]& buffer, String& secret)
   at MTProtoProxy.MTProtoProxyServer.SocketAccepted(Socket socket)
A new connection was created
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at MTProtoProxy.TgSockets.GetSocket(Int32& dcId)
   at MTProtoProxy.MTProtoSocket.StartAsync(Byte[]& buffer, String& secret)
   at MTProtoProxy.MTProtoProxyServer.SocketAccepted(Socket socket)
