### ISSUE TITLE
DC id out of range

### ISSUE THREAD

**Issue by ghost** [TGMTProto/MTProtoProxy#19]
Hi,
When connecting with mobile, datacenter id will be out of range (-1) and it won't connect.

Device:
ios: Telegram X latest version

Also tested in android beta. Not working.

More info:
```
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRange_IndexException()
   at MTProtoProxy.TgSockets.GetSocket(Int32& dcId)
   at MTProtoProxy.MTProtoSocket.StartAsync(Byte[]& buffer, String& secret)
   at MTProtoProxy.MTProtoProxyServer.SocketAccepted(Socket socket)
A new connection was created
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
```

**Comment by NGame1** [comment]
You have the same issue : 
https://github.com/TGMTProto/MTProtoProxy/issues/18
Seems it happens on Users(IPs) count more than 10

**Comment by ghost** [comment]
@NGame1 I am the only user. This issue only happens on mobile. Telegram Desktop is ok!
